### config.toml
title = "LOADays"
baseURL = "https://loadays.org/"
theme = "loadays"
languageCode = "2019"
defaultContentLanguage = "2019"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true
dataDir = "data"
assetDir = "assets"
PaginatePath = "blog"
sectionPagesMenu = "main"
buildDrafts = false
pygmentsUseClasses = true
enableGitInfo = true
enableRobotsTXT = true

[outputs]
section = [ "HTML", "Calendar" , "RSS" ]

[outputFormats]
[outputFormats.RSS]
	mediatype = "application/rss"
	baseName = "feed"
	suffix = "xml"
