# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: loadays.org

  # A short description of the repository that will show up on GitHub
  description: The repo for website for loadays.org

  # A URL with more information about the repository
  homepage: https://github.com/loadays/loadays.org/wiki

  # A comma-separated list of topics to set on the repository
  topics: golang, go, sysadmin, system engineering, sre, configuration-management, config-management, devops, etcd, distributed-systems

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false

  # Updates the default branch for this repository.
  default_branch: master

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests (in alphabetical order)
labels:
  - name: schedule
    color: fc2929
  - name: sponsor
    color: d93f0b
  - name: theme
    color: 5319e7
  - name: duplicate
    color: cccccc
  - name: enhancement
    color: 84b6eb

# Collaborators: give specific users access to this repository.
#collaborators:
#  - username: toshywoshy
#    # Note: Only valid on organization-owned repositories.
#    # The permission to grant the collaborator. Can be one of:
#    # * `pull` - can pull, but not push to or administer this repository.
#    # * `push` - can pull and push, but not administer this repository.
#    # * `admin` - can pull, push and administer this repository.
#    permission: push

#  - username: hubot
#    permission: pull
